Feature LLE 262 - Add NPS Campaign popup style
lean-library/lean-library-extension-styling pull request #16
Opened 2021-06-22 12:32 UTC by DimitrijeMihic

2021-06-23 13:04 UTC, nothingrandom reviewed
Why is everything `!important`? What is it we're having to override this way?

2021-06-23 13:35 UTC, DimitrijeMihic commented
We're injecting elements directly in the page, and the page has its own style, different from ours. In most cases the page style overrides our style, that's why we have `!important` in almost every line.

2021-06-23 14:12 UTC, nothingrandom requested changes
Mentions of `font-family: 'Montserrat';` would make more sense as;

```scss
$font-sans: 'Montserrat', sans-serif;
font-family: $font-sans;
```

2021-06-23 14:12 UTC, nothingrandom commented on src/workflow.scss
> +  color:#fff !important;
```suggestion
  color: #fff !important;
```

2021-06-23 14:12 UTC, nothingrandom commented on src/workflow.scss
> +  display:none !important;
```suggestion
  display: none !important;
```

2021-06-23 14:12 UTC, nothingrandom commented on src/workflow.scss
> +  border: none !important;
```suggestion
  width: 100%;
  color: #3B3B3B;
  text-decoration: none !important;
  font-weight: 500 !important;
  font-family: 'Montserrat' !important;
  font-size: 14px !important;
  display: flex !important;
  align-items: center !important;
  border: none !important;
```

2021-06-23 14:12 UTC, nothingrandom commented on src/workflow.scss
> +  border: none !important;
```suggestion
  width: 100%;
  color: #3B3B3B;
  text-decoration: none !important;
  font-weight: 500 !important;
  font-family: 'Montserrat' !important;
  font-size: 14px !important;
  border: none !important;
```

2021-06-23 14:12 UTC, nothingrandom commented on src/workflow.scss
> +  font-size:13px !important;
```suggestion
  font-size: 13px !important;
```

2021-06-24 08:36 UTC, nothingrandom approved these changes

2021-06-24 08:43 UTC, DraganaBelic approved these changes

2021-06-24 08:44 UTC, merged